version: 5
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  # password: <redacted>
serial:
  port: /dev/ttyACM0
  adapter: ember
  baudrate: 460800
  rtscts: true
advanced:
  log_level: info
  channel: 25
  # network_key: <redacted>
  pan_id: 56388
  # ext_pan_id: <redacted>
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0x0017880109adc657':
    friendly_name: Laundry Room Light
  '0x001788010b9da96f':
    friendly_name: Hallway Light
  '0x001788010b9d596e':
    friendly_name: Kitchen Light
  '0x0017880109aedc70':
    friendly_name: Bedroom Light
  '0x0017880109aedb1d':
    friendly_name: Bathroom Light
  '0x001788010f6a019e':
    friendly_name: Living Room Motion
  '0x001788010f69cdb8':
    friendly_name: Hallway Motion
  '0x001788010f69c509':
    friendly_name: Bathroom Motion
  '0x001788010f69cc74':
    friendly_name: Laundry Room Motion
  '0x001788010b7d2b95':
    friendly_name: '0x001788010b7d2b95'
  '0x58263afffe4681f1':
    friendly_name: '0x58263afffe4681f1'
